### ISSUE TITLE
Add commands for compiling the jar to the README

### ISSUE THREAD

**Issue by jfriedly** [RobertZenz/EasyMineLauncher#1]
Hi, I'm trying to use this launcher because MagicLauncher won't recognize my 1.4.2 minecraft.jar and it's too GUI-oriented to actually know what it's doing.  But I'm pretty new to Java, and having cloned your repo, and can't figure out how to compile the source into Java bytecode and put it all into a jar.

Closest I've gotten is:

```
$ javac src/org/bonsaimind/easyminelauncher/*
$ # created a manifest file because Java seems to want one, this one didn't work:
$ mkdir META-INF
$ echo "Main-Class: src.org.bonsaimind.easyminelauncher.Main" > META-INF/MANIFEST.MF
$ jar cvf EasyMineLanucher.jar META-INF src
```

Could you help me out a bit (or maybe add the instructions to your README)?

Thanks,
Joel

**Comment by RobertZenz** [comment]
You're right, I'm missing a proper build-script (have been using NetBeans all along). I'll add an appropriate script.

**Comment by RobertZenz** [comment]
Ive added a build.xml, so if you have [Ant](http://ant.apache.org/) installed, compiling it is as easy as running `ant` in the directory.

If you don't and don't want to, here is a step-by-step guide:
1. Create a manifest file `MANIFEST.MF` in the base directory with the following content:
   
   ```
   Manifest-Version: 1.0
   Main-Class: org.bonsaimind.easyminelauncher.Main
   ```
2. Execute the following commands:
   
   ```
   $ mkdir build dist
   $ javac -d build src/org/bonsaimind/easyminelauncher/*
   $ jar -cvfm dist/EasyMineLauncher.jar MANIFEST.MF -C build build/org/bonsaimind/easyminelauncher/*
   ```
3. Find the ready-to-use jar in `dist`.

**Comment by jfriedly** [comment]
Thank you!
