### ISSUE TITLE
Username error

### ISSUE THREAD

**Issue by monowii** [RobertZenz/EasyMineLauncher#5]
Hi, i can't loggin correctly with my mojang account. I set my username as my email for loggin (--username=myEmail@google.com) but it keep my email as username (I checked in chat in singleplayer).

**Comment by RobertZenz** [comment]
Hello.

The login is working fine? If yes I know what it is.
And can you keep playing on the server? I mean, can you play for a quarter hour, go to the main menu and join the server again? The last would be interesting to know if the keep-alive of the authentication works with your E-Mail address or username.

**Comment by RobertZenz** [comment]
I just pushed v0.14. Please try if this is fixed in that release.

**Comment by monowii** [comment]
Perfect ! Working perfectly now. Thanks :D !
