### ISSUE TITLE
authentication-failure not working

### ISSUE THREAD

**Issue by monowii** [RobertZenz/EasyMineLauncher#6]
Hi, i found another bug: impossible to use --authentication-failure=

Exception in thread "main" java.lang.IllegalArgumentException: No enum constant
org.bonsaimind.easyminelauncher.AuthenticationFailureBehavior.e=ALERT_CONTINUE
        at java.lang.Enum.valueOf(Unknown Source)
        at org.bonsaimind.easyminelauncher.AuthenticationFailureBehavior.valueOf
(Unknown Source)
        at org.bonsaimind.easyminelauncher.Main.main(Unknown Source)
Appuyez sur une touche pour continuer...

P.S. If possible, can you add a function to load dirrectly the lastlogin file with a parameter ?

**Comment by RobertZenz** [comment]
Wow...I never hated Exceptions so much before...

First, I've fixed that behavior in v0.15...my bad by the way (who else?).

Second, you now have a --use-lastlogin.
