### ISSUE TITLE
EML will not work with 1.6.

### ISSUE THREAD

**Issue by RobertZenz** [RobertZenz/EasyMineLauncher#7]
Yeah, I know...

**Comment by RobertZenz** [comment]
Due to the changed nature of the Minecraft-Client, EasyMineLauncher will not work with beta and the final version of 1.6 (to be released in week 26 2013) and up.

Looking at this, it looks more like writing EML2 from scratch would be a better option then to trying to adopt EML. Not only has the directory structure changed significantly (the minecraft.jar is no longer containing everything needed (except dependencies)) but also has the way changed Minecraft launches. F.e. the creation of the window is now part of Minecraft itself and is no longer the responsibility of the launcher. That means that I'm no longer able to control the window from the launcher, axing most window options[1]. What does "most" mean? From looking at it, it seems like it still does accept width/height parameters...I'm not sure about that, needs more checking.

I also need to check what of the files still exist and how the changed profile system effects launching of Minecraft...all in all, some work to be done when I have the time for it.

[1]: Insert a snarky comment here that you should use an OS which provides a sane window manager anyway.

**Comment by RobertZenz** [comment]
After looking at it some more, it seems like many things have and will change with 1.6, these changes will not be implemented into EML.

**Comment by jcc10** [comment]
You can probabbly look at: http://www.kaise123.com/minecraft/McOpenLauncher/

It could be a temporary solution, but I don't know if the creator will keep maintaining it...

**Comment by RobertZenz** [comment]
@jcc10 Thanks. After looking at the new version it's not a matter of "how" but rather "should I". See [EasyMineLauncher2](https://github.com/RobertZenz/EasyMineLauncher2) why I voted against rewriting EML for the time being.

It's the question if the existence of such a tool is still warranted, as the things I exposed are either now implemented in the Minecraft Launcher or removed.

**Comment by stephenmac7** [comment]
I personally don't like the new launcher at all. The way it works, the way it made downloading the files manually harder, etc. I would love it if this project was continued, if not only for the fact that it's terminal-based, allowing access to Minecraft through other languages (such as Python). I am currently maintaining another project (https://github.com/stephenmac7/mml) which requires this and, honestly, I just love having control over the way Minecraft launches.

**Comment by jcc10** [comment]
:D I was just about to say the same thing about the command line startup, but for me one of the big parts is that the new one refuses to give me offline mode, it is also going to be a pain to move a install of minecraft from one computer to another. </rant> but even if you are not going to make a new launcher, thank you for making and updating this one.

**Comment by stephenmac7** [comment]
I second the above, and the new blend argument is just so useful! Thank you for that RobertZenz.
